<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pupil_labs_ros</name>
  <version>0.0.0</version>
  <description>ROS 2 driver for Pupil Labs glasses</description>
  <maintainer email="mooeyad@gmail.com">Mohamed Eyad</maintainer>
  <license>MIT</license>
  <depend>rclpy</depend>
  <depend>ros2_hc_msgs</depend>
  <depend>std_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>cv_bridge</depend>
  <depend>cv2</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
