<?xml version="1.0"?>
<package format="3">
  <name>neurosity_driver</name>
  <version>0.1.0</version>
  <description>ROS2 driver for Neurosity EEG</description>
  <maintainer email="moperez@ethz.ch">Monica Perez-Serrano</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>
  <depend>rclpy</depend>
  <depend>healthcare_msgs</depend>
  <exec_depend>python-dotenv</exec_depend>
  <exec_depend>neurosity</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
